In [4]:
import tensorflow as tf
import numpy as np
keras = tf.keras

In [83]:
help(tf.r)

AttributeError: module 'tensorflow' has no attribute 'sum'

In [131]:
class FeatureL2Norm(keras.layers.Layer):
    def __init__(self):
        super(FeatureL2Norm, self).__init__()
    def call(self, feature):
        epsilon = 1e-6
        norm = tf.expand_dims(tf.pow(tf.reduce_sum(tf.pow(feature, 2), axis=-1)+epsilon, 0.5), axis=-1)
        return tf.math.divide(feature, norm)

In [132]:
feature = np.ones([64, 3, 3, 4], dtype=np.float32)
print(feature)

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 ...


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


In [133]:
L2Norm = FeatureL2Norm()

In [134]:
x = L2Norm(feature)
print(x)

tf.Tensor(
[[[[0.49999994 0.49999994 0.49999994 0.49999994]
   [0.49999994 0.49999994 0.49999994 0.49999994]
   [0.49999994 0.49999994 0.49999994 0.49999994]]

  [[0.49999994 0.49999994 0.49999994 0.49999994]
   [0.49999994 0.49999994 0.49999994 0.49999994]
   [0.49999994 0.49999994 0.49999994 0.49999994]]

  [[0.49999994 0.49999994 0.49999994 0.49999994]
   [0.49999994 0.49999994 0.49999994 0.49999994]
   [0.49999994 0.49999994 0.49999994 0.49999994]]]


 [[[0.49999994 0.49999994 0.49999994 0.49999994]
   [0.49999994 0.49999994 0.49999994 0.49999994]
   [0.49999994 0.49999994 0.49999994 0.49999994]]

  [[0.49999994 0.49999994 0.49999994 0.49999994]
   [0.49999994 0.49999994 0.49999994 0.49999994]
   [0.49999994 0.49999994 0.49999994 0.49999994]]

  [[0.49999994 0.49999994 0.49999994 0.49999994]
   [0.49999994 0.49999994 0.49999994 0.49999994]
   [0.49999994 0.49999994 0.49999994 0.49999994]]]


 [[[0.49999994 0.49999994 0.49999994 0.49999994]
   [0.49999994 0.49999994 0.49999994 0.499

In [135]:
(0.49999994**2)*4

0.9999997600000143