In [1]:
from test_codes import data, train, model
import json, os
import argparse

In [2]:
with open('overfit.json') as fp:
    config = json.load(fp)
split = 'val'

In [3]:
#data.synthesize_image_pair(config, split)

In [4]:
print(config['train'])

{'n_examples': 1000, 'learning_rate': 0.001, 'batch_size': 16, 'epochs': 100, 'print_step': 10}


In [ ]:
config['train']['n_example'] = 1000
config['train']['batch_size'] = 16

In [ ]:
config['train']['epochs'] = 400

In [ ]:
config['exp_desc'] = 'change_regressor_more_examples'

In [ ]:
config['backbone'] = 'vgg16'

In [5]:
train.overfit(config, ['train'])

train dataset amount : 1000
val dataset amount : 1000
start of epoch 1
score :  [[0.0702060238 0.0659246743 0.0648275316 ... 0.0638492554 0.0612334423 0.0590367652]
 [0.0634454861 0.0591246188 0.0568441786 ... 0.0597686432 0.0606067 0.060231328]
 [0.0609136224 0.0563783832 0.0531569831 ... 0.0596234612 0.061930649 0.0579533875]
 ...
 [0.0609377362 0.056568183 0.0552205257 ... 0.0577552021 0.0576557145 0.0564873666]
 [0.0611230955 0.0576295 0.0567660183 ... 0.0605675541 0.0594131313 0.0559498817]
 [0.0612256303 0.0562343411 0.0567957126 ... 0.0581752174 0.0577408373 0.0564103462]]
pred :  [[[-0.195257083 0.00147898495]
  [-0.00495304 -0.0823720098]
  [0.0254087783 -0.0549377352]
  ...
  [0.0852742717 -0.0208340846]
  [0.117815554 0.0402158126]
  [0.0406532772 -0.0717763826]]

 [[-0.199729115 0.00126703456]
  [-0.00179595686 -0.0859896913]
  [0.0207036268 -0.0531938076]
  ...
  [0.0845166296 -0.0177103411]
  [0.119406849 0.0369328968]
  [0.0415111035 -0.0721522644]]

 [[-0.195526153 0.00

score :  [[0.0632961392 0.0627175495 0.0630678385 ... 0.0625884 0.0627370924 0.0621261895]
 [0.0621915236 0.0622176677 0.0621911138 ... 0.0618907 0.062034823 0.0617183]
 [0.0623244196 0.0624065325 0.0619709641 ... 0.0618885309 0.0619008541 0.0616430901]
 ...
 [0.0623554774 0.0618729517 0.061855156 ... 0.0619658306 0.0619962 0.061661344]
 [0.0623723045 0.0618694685 0.0619993247 ... 0.0619070455 0.0619913 0.061733596]
 [0.0617945716 0.0618911274 0.0624515042 ... 0.0619935393 0.0620399676 0.0617054924]]
pred :  [[[-0.0131377876 0.0171150304]
  [0.0351204351 0.0309081748]
  [-0.0557216369 -0.0117470752]
  ...
  [0.0281285066 0.0396374948]
  [0.0412339494 0.0178642515]
  [0.0474165641 -0.0232360661]]

 [[-0.013054464 0.0172220133]
  [0.0351991877 0.0311081428]
  [-0.0558245964 -0.0115821064]
  ...
  [0.0283746067 0.0397867523]
  [0.0414068773 0.0178636499]
  [0.047418192 -0.0232808]]

 [[-0.0133394226 0.017078653]
  [0.035026975 0.0306220539]
  [-0.0552201234 -0.0115655717]
  ...
  [0.02804

score :  [[0.0637952536 0.0630373135 0.062921 ... 0.0628952533 0.0629046708 0.0626182109]
 [0.0631837472 0.0623790845 0.0620972253 ... 0.0620824955 0.0620872751 0.0618458949]
 [0.0628974587 0.0622304343 0.0621450916 ... 0.06213177 0.0621108487 0.0619035885]
 ...
 [0.0625793114 0.0622541644 0.0621326342 ... 0.0623239726 0.0622834414 0.0621290803]
 [0.0625727698 0.0622397326 0.0620982908 ... 0.0623413883 0.0620259643 0.0613274202]
 [0.0623665191 0.062302582 0.062203031 ... 0.0623199232 0.0623351373 0.0619340204]]
pred :  [[[0.0284515843 -0.0414399318]
  [0.0297699962 -0.0428561345]
  [-0.0203154441 -0.0303777736]
  ...
  [0.0328115188 -0.0117926523]
  [-0.010762739 -0.0476521924]
  [0.00575313717 0.0293692444]]

 [[0.0286158845 -0.0412857682]
  [0.029898677 -0.0429019555]
  [-0.0199465752 -0.0302422252]
  ...
  [0.032462474 -0.0118170409]
  [-0.0108878771 -0.0477834344]
  [0.00599365029 0.0292888246]]

 [[0.0286429655 -0.0413078554]
  [0.0298760403 -0.0425953455]
  [-0.0198938437 -0.0301

score :  [[0.0630762428 0.062434379 0.0624174885 ... 0.0622371919 0.0625348762 0.0619823821]
 [0.0624404 0.0615230054 0.0616659299 ... 0.0615765117 0.0618528761 0.061245773]
 [0.0622126 0.0615225248 0.0613632351 ... 0.0619344078 0.0617010295 0.0610678494]
 ...
 [0.0621001534 0.0616323166 0.0615632422 ... 0.0617628545 0.0616756268 0.0610407889]
 [0.0619707294 0.0616964586 0.061608322 ... 0.0619425327 0.0617416315 0.0615903363]
 [0.0620707609 0.0620131381 0.0614859872 ... 0.0618990473 0.0613881461 0.0612348355]]
pred :  [[[-0.00909679569 0.00143509055]
  [-0.0184213966 -0.00680580642]
  [0.00722763594 0.00105364213]
  ...
  [0.000722239842 0.0138526922]
  [0.00493363664 -0.00472056493]
  [-0.00633128546 0.00570580782]]

 [[-0.00911779795 0.00143816066]
  [-0.018436823 -0.00675220042]
  [0.00730496086 0.00103006477]
  ...
  [0.000746968319 0.0138793876]
  [0.00494813 -0.00467229635]
  [-0.00631658 0.0056902566]]

 [[-0.00910483487 0.00144173508]
  [-0.0184555333 -0.00679048616]
  [0.00729

score :  [[0.0633744 0.0626504049 0.0626768917 ... 0.0626231879 0.0626558289 0.0624366738]
 [0.0625091642 0.0619069412 0.0619308 ... 0.0618379712 0.0618475676 0.0616702177]
 [0.0625652745 0.0619222857 0.0619725883 ... 0.0618522055 0.0618661121 0.0616940409]
 ...
 [0.0623936355 0.0619225763 0.0619117245 ... 0.0618511923 0.0618658215 0.0616939552]
 [0.0627113357 0.0621047281 0.0619586632 ... 0.0618825443 0.0618912727 0.0617283918]
 [0.0622354113 0.0619766563 0.0620963834 ... 0.0619265474 0.0619327 0.061905358]]
pred :  [[[-0.0166463852 0.0253830682]
  [-0.00737519423 -0.00584976841]
  [-0.00111899711 0.00416860543]
  ...
  [-0.0189625118 0.00752060208]
  [0.00359469233 0.0128047755]
  [-0.0155453971 -0.00573114306]]

 [[-0.0166463852 0.0253830682]
  [-0.00737519423 -0.00584976841]
  [-0.00111899711 0.00416860543]
  ...
  [-0.0189625118 0.00752060208]
  [0.00359469233 0.0128047755]
  [-0.0155453971 -0.00573114306]]

 [[-0.0166463852 0.0253830682]
  [-0.00737519423 -0.00584976841]
  [-0.00

score :  [[0.0634049 0.0624125674 0.062682353 ... 0.0623404719 0.0623573959 0.0620623715]
 [0.0627596 0.0619093105 0.0622340702 ... 0.0616714507 0.0616438389 0.0614263453]
 [0.0623352304 0.0614837334 0.0621458255 ... 0.0616869181 0.0616613552 0.0614070892]
 ...
 [0.0622909665 0.0616781749 0.0616469458 ... 0.0620778054 0.0616862513 0.0611896]
 [0.0622534975 0.0617379062 0.0616148487 ... 0.0621569268 0.0618717261 0.0609570257]
 [0.0621225052 0.0617767833 0.0617010221 ... 0.0621016398 0.0618910119 0.0610840246]]
pred :  [[[-0.00214965851 0.0156731885]
  [-0.0148147568 -0.000254748389]
  [0.00296209869 0.0154992035]
  ...
  [-0.0305551291 0.0117094358]
  [-0.00683830027 0.000723079778]
  [-0.0257617608 0.00286210841]]

 [[-0.00214965851 0.0156731885]
  [-0.0148147568 -0.000254748389]
  [0.00296209869 0.0154992035]
  ...
  [-0.0305551291 0.0117094358]
  [-0.00683830027 0.000723079778]
  [-0.0257617608 0.00286210841]]

 [[-0.00214965851 0.0156731885]
  [-0.0148147568 -0.000254748389]
  [0.00

score :  [[0.0629966483 0.0624529 0.0625430122 ... 0.0628344119 0.0626166388 0.0623158]
 [0.0623257235 0.0618023388 0.0618934967 ... 0.0621944815 0.0620130524 0.0617638119]
 [0.0623046197 0.0618112311 0.0619681701 ... 0.0622459836 0.0620672964 0.0619449243]
 ...
 [0.0625419617 0.0620262548 0.0619908385 ... 0.0621469468 0.0618058369 0.0617055595]
 [0.062501274 0.0619492605 0.0619984567 ... 0.0620687157 0.0617524795 0.0616181567]
 [0.0622426681 0.0619962215 0.0619393811 ... 0.0621334873 0.0620380379 0.0616749264]]
pred :  [[[0.00544896442 0.0133997723]
  [-0.0131109813 0.00193290552]
  [0.0090031689 0.0139573952]
  ...
  [-0.0215136465 0.000262457703]
  [-0.00505137 0.00131328334]
  [-0.0211529452 0.00652619824]]

 [[0.00544896442 0.0133997723]
  [-0.0131109813 0.00193290552]
  [0.0090031689 0.0139573952]
  ...
  [-0.0215136465 0.000262457703]
  [-0.00505137 0.00131328334]
  [-0.0211529452 0.00652619824]]

 [[0.00544896442 0.0133997723]
  [-0.0131109813 0.00193290552]
  [0.0090031689 0.0

Training loss (for one batch) at step 20: 0.5049152970314026
score :  [[0.06319049 0.0632218421 0.0624608733 ... 0.0624941476 0.0625543669 0.0623129196]
 [0.0627130345 0.0619968101 0.0612691455 ... 0.0616423152 0.0617785119 0.0615884103]
 [0.0619133711 0.0609158 0.0608326867 ... 0.061779391 0.0618609153 0.0615654178]
 ...
 [0.0620283335 0.0617232658 0.0624167 ... 0.0613417812 0.0612092353 0.0608222522]
 [0.0625519 0.0618999228 0.062205933 ... 0.0614542775 0.0616206117 0.0616591126]
 [0.0620366521 0.0613876805 0.0616228282 ... 0.0612733848 0.0613429211 0.0612095185]]
pred :  [[[0.000766282668 0.00858106185]
  [0.00279690512 -0.000560418237]
  [-0.00515011512 0.0104804812]
  ...
  [-0.00206589 -0.009430659]
  [-0.00672338251 0.00914200116]
  [-0.000726202619 0.00407952769]]

 [[0.000766282668 0.00858106185]
  [0.00279690512 -0.000560418237]
  [-0.00515011512 0.0104804812]
  ...
  [-0.00206589 -0.009430659]
  [-0.00672338251 0.00914200116]
  [-0.000726202619 0.00407952769]]

 [[0.00076628

score :  [[0.0631732568 0.0626033321 0.0624895431 ... 0.0625691414 0.0626513883 0.062486697]
 [0.0625340417 0.0619976819 0.0619530194 ... 0.0619758256 0.0620526522 0.0619260073]
 [0.0625342578 0.0619958825 0.0619459413 ... 0.0620823652 0.0620804615 0.0618933477]
 ...
 [0.0625612363 0.0620369799 0.0620111488 ... 0.0621550381 0.0620705 0.0618685074]
 [0.0625609 0.0620332323 0.0620121732 ... 0.0620875619 0.0620435886 0.0618707128]
 [0.0623175502 0.0620194897 0.0619973 ... 0.0621523857 0.0618714131 0.0617463849]]
pred :  [[[0.00709716137 0.00287007797]
  [0.0149581842 -0.00286200689]
  [-0.0164561886 0.00972213689]
  ...
  [0.0132894153 -0.0100626573]
  [-0.0167079624 0.011533102]
  [0.0139360055 0.00803361367]]

 [[0.00709716137 0.00287007797]
  [0.0149581842 -0.00286200689]
  [-0.0164561886 0.00972213689]
  ...
  [0.0132894153 -0.0100626573]
  [-0.0167079624 0.011533102]
  [0.0139360055 0.00803361367]]

 [[0.00709716137 0.00287007797]
  [0.0149581842 -0.00286200689]
  [-0.0164561886 0.00

score :  [[0.0632535219 0.0629625171 0.0627679154 ... 0.0627184659 0.062644437 0.0623657554]
 [0.0627261251 0.0624486692 0.0623485744 ... 0.0620275363 0.0619633831 0.0618651211]
 [0.0628300607 0.0623287521 0.0620632358 ... 0.0618452504 0.0617669299 0.0615785122]
 ...
 [0.062377125 0.0617891 0.061549902 ... 0.062154565 0.0619195923 0.0616819784]
 [0.0622851886 0.0615692846 0.0614648536 ... 0.0620643236 0.0618806034 0.0617053844]
 [0.0621060655 0.0616051294 0.06148405 ... 0.0619391464 0.061888 0.0617656149]]
pred :  [[[0.0149659123 0.00239988277]
  [0.0139905168 -0.00233263569]
  [-0.0139476052 0.0136883147]
  ...
  [0.0144252293 -0.00844477769]
  [-0.023467619 0.0116488803]
  [0.0128100654 0.0144106597]]

 [[0.0149659123 0.00239988277]
  [0.0139905168 -0.00233263569]
  [-0.0139476052 0.0136883147]
  ...
  [0.0144252293 -0.00844477769]
  [-0.023467619 0.0116488803]
  [0.0128100654 0.0144106597]]

 [[0.0149659123 0.00239988277]
  [0.0139905168 -0.00233263569]
  [-0.0139476052 0.0136883147

score :  [[0.0632243752 0.0626556575 0.0626487732 ... 0.0631048828 0.062662 0.0623655207]
 [0.0626246 0.0619871616 0.0619621538 ... 0.0623048022 0.0619295835 0.0616412722]
 [0.0626349822 0.0620118715 0.0619967729 ... 0.0620013289 0.0616937 0.0614639781]
 ...
 [0.0625831 0.0619884096 0.0619614124 ... 0.062270958 0.0621568598 0.0617828481]
 [0.0625738204 0.0619873367 0.0619538128 ... 0.0619706288 0.0618572347 0.0615274385]
 [0.0623050369 0.0618521832 0.061823789 ... 0.0617370754 0.0617370456 0.0617262684]]
pred :  [[[0.0184469856 0.002588209]
  [0.00765321637 -0.00237335078]
  [-0.00653333962 0.0131478151]
  ...
  [0.00782439951 -0.000343431951]
  [-0.0131535977 0.00330120721]
  [0.00586300157 0.014282221]]

 [[0.0184469856 0.002588209]
  [0.00765321637 -0.00237335078]
  [-0.00653333962 0.0131478151]
  ...
  [0.00782439951 -0.000343431951]
  [-0.0131535977 0.00330120721]
  [0.00586300157 0.014282221]]

 [[0.0184469856 0.002588209]
  [0.00765321637 -0.00237335078]
  [-0.00653333962 0.0131

score :  [[0.063214168 0.0626518726 0.0626251101 ... 0.0626725778 0.062699683 0.0625108108]
 [0.0625616685 0.0620075 0.0619874 ... 0.0620414764 0.0620803088 0.0619311556]
 [0.062554881 0.0620045625 0.0619918518 ... 0.0620463416 0.0620556064 0.0619187243]
 ...
 [0.0625595748 0.0620090924 0.0619781576 ... 0.0619406849 0.0619502887 0.0618145689]
 [0.0625861511 0.0620441213 0.0620094165 ... 0.0619188845 0.0620455183 0.0618858375]
 [0.0623662733 0.0619996712 0.0619792603 ... 0.0619325712 0.0619736351 0.0618541129]]
pred :  [[[0.00310035958 0.00713706296]
  [0.0084451288 -0.00759998942]
  [-0.00454050396 -0.00145760784]
  ...
  [0.00223391596 -0.0117810275]
  [0.00478090253 0.00378779322]
  [0.00135405874 -0.000443338417]]

 [[0.00310035958 0.00713706296]
  [0.0084451288 -0.00759998942]
  [-0.00454050396 -0.00145760784]
  ...
  [0.00223391596 -0.0117810275]
  [0.00478090253 0.00378779322]
  [0.00135405874 -0.000443338417]]

 [[0.00310035958 0.00713706296]
  [0.0084451288 -0.00759998942]
  [-

score :  [[0.063317962 0.0627602711 0.0628255606 ... 0.0622230433 0.0626598671 0.0625177249]
 [0.0628555194 0.0622355975 0.0621934794 ... 0.0617666431 0.0622693039 0.0619882904]
 [0.0626904294 0.0621345714 0.0620510876 ... 0.0618341118 0.0621728711 0.0619088225]
 ...
 [0.062625736 0.0622107834 0.0622816086 ... 0.0621165223 0.0621078052 0.0619623736]
 [0.0626675412 0.0621909089 0.0622847304 ... 0.061976064 0.0622503161 0.0619821809]
 [0.0624114163 0.0619112439 0.0620731115 ... 0.0617591366 0.0620591976 0.0618727244]]
pred :  [[[-0.00497839786 -0.000196259469]
  [0.0119638983 -0.00405413704]
  [-0.0103458008 -0.00476521719]
  ...
  [0.00180000113 -0.0114859156]
  [0.00766563648 -0.000481233466]
  [0.00130806665 -0.0100857709]]

 [[-0.00497839786 -0.000196259469]
  [0.0119638983 -0.00405413704]
  [-0.0103458008 -0.00476521719]
  ...
  [0.00180000113 -0.0114859156]
  [0.00766563648 -0.000481233466]
  [0.00130806665 -0.0100857709]]

 [[-0.00497839786 -0.000196259469]
  [0.0119638983 -0.0040

score :  [[0.0631265789 0.0626123548 0.0623720847 ... 0.0624961555 0.0626212284 0.0626053661]
 [0.0626557097 0.0623101704 0.0623422191 ... 0.0618856102 0.0619682893 0.061885763]
 [0.0626025 0.0622744188 0.0623097159 ... 0.0619409382 0.0619128384 0.0617907718]
 ...
 [0.0625953823 0.0621678308 0.0622585453 ... 0.0616933405 0.061905887 0.0614122674]
 [0.0625645295 0.0621159561 0.0623082407 ... 0.0615622774 0.0617031604 0.0615785271]
 [0.062618807 0.0620819256 0.0623934232 ... 0.0616799146 0.0618446209 0.0617263727]]
pred :  [[[-0.000775913941 -0.00791318342]
  [0.0089650061 0.00818099454]
  [-0.00983964093 0.00666273292]
  ...
  [-0.00356647978 -0.000108203152]
  [-0.00278023444 -0.00573166087]
  [-0.00796641409 -0.00727371173]]

 [[-0.000775913941 -0.00791318342]
  [0.0089650061 0.00818099454]
  [-0.00983964093 0.00666273292]
  ...
  [-0.00356647978 -0.000108203152]
  [-0.00278023444 -0.00573166087]
  [-0.00796641409 -0.00727371173]]

 [[-0.000775913941 -0.00791318342]
  [0.0089650061 0.

score :  [[0.0633014962 0.0621483214 0.0629723221 ... 0.0620955341 0.0622065663 0.062022727]
 [0.0625333264 0.0618009642 0.0619081706 ... 0.0615787916 0.0615631752 0.0613609254]
 [0.0624175 0.0619300455 0.0617980361 ... 0.0615980849 0.061536856 0.0614254698]
 ...
 [0.062513262 0.0615117289 0.0617680438 ... 0.0616780519 0.0619933605 0.0616370067]
 [0.0622335896 0.0614742748 0.0617447235 ... 0.0617095903 0.061769817 0.061477758]
 [0.0616934113 0.0613499098 0.0613944232 ... 0.0615835413 0.0614564531 0.0612777621]]
pred :  [[[-0.00398734584 -0.00994269736]
  [0.00281496556 0.0168566033]
  [-0.0109427627 0.0153858466]
  ...
  [-0.00522026373 0.00850163773]
  [-0.00590583123 -0.0098359175]
  [-0.0168680586 -0.00263713486]]

 [[-0.00398734584 -0.00994269736]
  [0.00281496556 0.0168566033]
  [-0.0109427627 0.0153858466]
  ...
  [-0.00522026373 0.00850163773]
  [-0.00590583123 -0.0098359175]
  [-0.0168680586 -0.00263713486]]

 [[-0.00398734584 -0.00994269736]
  [0.00281496556 0.0168566033]
  [-

score :  [[0.0632506907 0.0628915727 0.0626540855 ... 0.0625054687 0.0623531342 0.0618028603]
 [0.062622942 0.0621337742 0.0619810559 ... 0.0619685538 0.0618464686 0.0614025258]
 [0.0622813553 0.0617764816 0.0616053529 ... 0.0621014908 0.0618897416 0.0614627786]
 ...
 [0.0622143447 0.0617277846 0.0617871359 ... 0.0623389184 0.0620445 0.0617223]
 [0.0623191558 0.0617578886 0.061795108 ... 0.0622006319 0.0619625561 0.061738003]
 [0.0620403 0.061664585 0.0616806857 ... 0.0618004203 0.061734423 0.0615664124]]
pred :  [[[-0.00608621119 -0.010554295]
  [7.91605562e-05 0.0208322704]
  [-0.00924716145 0.0187128596]
  ...
  [-0.000304060697 0.0152529329]
  [-0.00630104635 -0.00621813256]
  [-0.020829184 0.00617958186]]

 [[-0.00608621119 -0.010554295]
  [7.91605562e-05 0.0208322704]
  [-0.00924716145 0.0187128596]
  ...
  [-0.000304060697 0.0152529329]
  [-0.00630104635 -0.00621813256]
  [-0.020829184 0.00617958186]]

 [[-0.00608621119 -0.010554295]
  [7.91605562e-05 0.0208322704]
  [-0.0092471

score :  [[0.0627764314 0.0621884316 0.0622011162 ... 0.0618256852 0.061598409 0.0611996166]
 [0.0618972406 0.0609934032 0.0607258864 ... 0.0602573082 0.0603711158 0.0604639128]
 [0.0618865192 0.0613732226 0.0613654703 ... 0.0601468347 0.0617291108 0.061360877]
 ...
 [0.0620641559 0.0615854599 0.0618799776 ... 0.0613597631 0.0612469129 0.0608865097]
 [0.0615673959 0.0607327558 0.0605749227 ... 0.0613388 0.0612283647 0.0608929023]
 [0.0609622225 0.0599597581 0.0601169355 ... 0.0608092174 0.0606994964 0.0605007894]]
pred :  [[[-0.00645803381 -0.003908196]
  [0.00592207909 0.0143414158]
  [-0.0132940169 0.00850213692]
  ...
  [0.010256459 0.0136024151]
  [-0.00124357431 -0.00138861639]
  [-0.0189185832 0.0101122539]]

 [[-0.00645803381 -0.003908196]
  [0.00592207909 0.0143414158]
  [-0.0132940169 0.00850213692]
  ...
  [0.010256459 0.0136024151]
  [-0.00124357431 -0.00138861639]
  [-0.0189185832 0.0101122539]]

 [[-0.00645803381 -0.003908196]
  [0.00592207909 0.0143414158]
  [-0.013294016

Training loss (for one batch) at step 50: 0.48660603165626526
score :  [[0.0631874576 0.0625955909 0.0625067875 ... 0.0626066104 0.0624626055 0.0621383339]
 [0.0625810921 0.0619915351 0.0619388297 ... 0.0617158599 0.0619247854 0.0618065372]
 [0.0624914169 0.0619745366 0.0619519502 ... 0.0622365698 0.0622771829 0.0618510172]
 ...
 [0.0627029315 0.0621087365 0.0618916 ... 0.0619298257 0.0620118193 0.0618337728]
 [0.0624749511 0.0619758554 0.0618465133 ... 0.061714869 0.0617674664 0.0616417564]
 [0.0620967336 0.0616840757 0.0616607033 ... 0.0617301203 0.0617461652 0.0616428778]]
pred :  [[[-0.0160252843 0.0121869789]
  [0.00925225392 0.00176809635]
  [-0.0109365685 -0.00868301]
  ...
  [0.0141454581 0.000502725539]
  [0.00815229863 0.00127629959]
  [-0.0166732986 0.00391711295]]

 [[-0.0160252843 0.0121869789]
  [0.00925225392 0.00176809635]
  [-0.0109365685 -0.00868301]
  ...
  [0.0141454581 0.000502725539]
  [0.00815229863 0.00127629959]
  [-0.0166732986 0.00391711295]]

 [[-0.016025284

score :  [[0.0631018803 0.0624950677 0.0624975339 ... 0.062476 0.0623306669 0.0620760582]
 [0.0623028427 0.0617195182 0.0617121086 ... 0.0617059134 0.0616000928 0.061385069]
 [0.0622314326 0.0615911037 0.0615967698 ... 0.061598517 0.0614751726 0.0613387935]
 ...
 [0.0620909892 0.0615980774 0.0617981702 ... 0.061328724 0.0614368841 0.0613590963]
 [0.0621803664 0.06149913 0.0613911487 ... 0.0610569827 0.0611198395 0.060969051]
 [0.0618111 0.0613359064 0.0614120923 ... 0.0611766912 0.0613507 0.0615066923]]
pred :  [[[-0.0118473247 0.0100541888]
  [0.00863051508 0.00526310923]
  [-0.00830005202 -0.00822430849]
  ...
  [0.015048584 0.00743762311]
  [0.00622436497 -0.00285311416]
  [-0.0189607032 0.00771043729]]

 [[-0.0118473247 0.0100541888]
  [0.00863051508 0.00526310923]
  [-0.00830005202 -0.00822430849]
  ...
  [0.015048584 0.00743762311]
  [0.00622436497 -0.00285311416]
  [-0.0189607032 0.00771043729]]

 [[-0.0118473247 0.0100541888]
  [0.00863051508 0.00526310923]
  [-0.00830005202 -0

score :  [[0.063071467 0.0625842959 0.0626085103 ... 0.0626484901 0.0626576543 0.062494047]
 [0.062483523 0.0621097423 0.0620882399 ... 0.0621635579 0.062168695 0.0620264634]
 [0.0626329705 0.062179964 0.0620108768 ... 0.0620032661 0.0619730726 0.0618110485]
 ...
 [0.0626355931 0.0621967241 0.0623529963 ... 0.0622464195 0.0621793456 0.0620539226]
 [0.0629351959 0.0623073615 0.0622574724 ... 0.0619993 0.0621373765 0.0619977377]
 [0.0625689775 0.0619987808 0.0621243678 ... 0.0618182421 0.0618644617 0.0617846362]]
pred :  [[[-0.00225109817 0.00609478354]
  [0.00484435447 0.0115698688]
  [0.000828502234 0.00248672068]
  ...
  [0.0121650118 0.0235468205]
  [-0.00027482002 -0.00627645105]
  [-0.0275818929 0.0170441978]]

 [[-0.00225109817 0.00609478354]
  [0.00484435447 0.0115698688]
  [0.000828502234 0.00248672068]
  ...
  [0.0121650118 0.0235468205]
  [-0.00027482002 -0.00627645105]
  [-0.0275818929 0.0170441978]]

 [[-0.00225109817 0.00609478354]
  [0.00484435447 0.0115698688]
  [0.000828

score :  [[0.0627913252 0.0627005771 0.0624532029 ... 0.0621699 0.0621489063 0.0618362352]
 [0.061946 0.0617603064 0.0619349778 ... 0.0614550821 0.0614378713 0.0612322688]
 [0.0623860359 0.0615878887 0.0621992573 ... 0.0614451207 0.0614420697 0.0612401254]
 ...
 [0.0621307679 0.0614727661 0.0614421144 ... 0.0614460036 0.0614537485 0.0612152405]
 [0.062119212 0.0614683889 0.0614457913 ... 0.0614188872 0.0614640713 0.0612276793]
 [0.0621057861 0.0615763701 0.0615339652 ... 0.0615401 0.0615687743 0.0613631]]
pred :  [[[0.0028589447 0.00862269569]
  [0.00105669606 0.0134574808]
  [0.011678867 0.0112168528]
  ...
  [0.00473898929 0.0334602892]
  [-0.00678539556 -0.00716592185]
  [-0.0325172 0.0223308932]]

 [[0.0028589447 0.00862269569]
  [0.00105669606 0.0134574808]
  [0.011678867 0.0112168528]
  ...
  [0.00473898929 0.0334602892]
  [-0.00678539556 -0.00716592185]
  [-0.0325172 0.0223308932]]

 [[0.0028589447 0.00862269569]
  [0.00105669606 0.0134574808]
  [0.011678867 0.0112168528]
  ...


Epoch 1, Loss: 0.5024479627609253, Val Loss: 0.4887549579143524
end of epoch.
start of epoch 2
score :  [[0.0625266954 0.0615333058 0.0637446791 ... 0.0617271401 0.0617254339 0.0615586862]
 [0.0612989292 0.0609961227 0.0622253418 ... 0.0604041703 0.0600780696 0.0595387965]
 [0.0612738505 0.0606826916 0.06116933 ... 0.0607672073 0.059743531 0.0593091846]
 ...
 [0.061092861 0.0605392754 0.0612142496 ... 0.0627817 0.0631111562 0.0629045516]
 [0.061278142 0.0608631186 0.0602278113 ... 0.0622489192 0.0615440346 0.060853783]
 [0.061251767 0.0602738746 0.0600378774 ... 0.0606648736 0.0603605583 0.0594240613]]
pred :  [[[-0.00701914309 0.0210671015]
  [-0.00486939633 0.00449656276]
  [0.0126484931 0.00200927327]
  ...
  [-0.00301881367 0.0117064519]
  [-0.00236706552 -0.0108005404]
  [-0.0272064675 0.00859468523]]

 [[-0.00701914309 0.0210671015]
  [-0.00486939633 0.00449656276]
  [0.0126484931 0.00200927327]
  ...
  [-0.00301881367 0.0117064519]
  [-0.00236706552 -0.0108005404]
  [-0.02720646

score :  [[0.0632897094 0.0626201257 0.0626463443 ... 0.0626084954 0.0624900386 0.0622187257]
 [0.0625338554 0.0620298125 0.0620209239 ... 0.0618472919 0.0619350523 0.0617857501]
 [0.0625083521 0.0618800446 0.0619717538 ... 0.0620877668 0.0620199665 0.0617022254]
 ...
 [0.0624458306 0.0617872886 0.0619271919 ... 0.0621787906 0.0621488132 0.0617335774]
 [0.0628534853 0.0623926297 0.0622962862 ... 0.0624366291 0.0621659681 0.0617725253]
 [0.0627354234 0.0622024909 0.0619944148 ... 0.0618892238 0.0617286377 0.0613889359]]
pred :  [[[-0.0115068872 0.0176233202]
  [-0.00406051567 -0.00430090632]
  [0.00243716384 -0.0117383339]
  ...
  [-0.00288018445 -0.012522893]
  [0.00392265711 -0.0110562397]
  [-0.0176212788 -0.0091585014]]

 [[-0.0115068872 0.0176233202]
  [-0.00406051567 -0.00430090632]
  [0.00243716384 -0.0117383339]
  ...
  [-0.00288018445 -0.012522893]
  [0.00392265711 -0.0110562397]
  [-0.0176212788 -0.0091585014]]

 [[-0.0115068872 0.0176233202]
  [-0.00406051567 -0.00430090632]


score :  [[0.0632313341 0.0628455356 0.0625925437 ... 0.0629876629 0.0628520399 0.0626212731]
 [0.062677823 0.0622506365 0.0622368567 ... 0.0623761676 0.0624174289 0.0621946082]
 [0.0625712052 0.062138889 0.0621736944 ... 0.0621806346 0.0619846769 0.0622669533]
 ...
 [0.0628983 0.0622003414 0.0618313663 ... 0.0621715076 0.0621678457 0.0618482493]
 [0.0628740862 0.0622799136 0.061814703 ... 0.0621209629 0.0620097294 0.0618987195]
 [0.0626141205 0.0620985031 0.0617256425 ... 0.0620622709 0.0620386 0.0619100668]]
pred :  [[[-0.00968080759 0.00802814]
  [-0.000216220506 -0.00660441723]
  [-0.00252354913 -0.0160748828]
  ...
  [-0.00218364154 -0.026367398]
  [0.00513717532 -0.00828575157]
  [-0.0106203705 -0.0131884059]]

 [[-0.00968080759 0.00802814]
  [-0.000216220506 -0.00660441723]
  [-0.00252354913 -0.0160748828]
  ...
  [-0.00218364154 -0.026367398]
  [0.00513717532 -0.00828575157]
  [-0.0106203705 -0.0131884059]]

 [[-0.00968080759 0.00802814]
  [-0.000216220506 -0.00660441723]
  [-0

score :  [[0.0631723 0.062796019 0.0628014281 ... 0.0627168715 0.0627043694 0.0625839308]
 [0.0627333298 0.0622372329 0.0622625537 ... 0.0621362478 0.0620876439 0.0619758628]
 [0.0627602637 0.0622866899 0.0622465387 ... 0.0622479841 0.0621390045 0.0621319972]
 ...
 [0.0629343316 0.0624980778 0.0624192432 ... 0.0622321442 0.0622655787 0.0621181913]
 [0.0627551 0.0623416156 0.0622945204 ... 0.0621359721 0.0621272027 0.0619987547]
 [0.0622732341 0.0620002337 0.0619474389 ... 0.0620706715 0.0621047 0.0619457811]]
pred :  [[[0.00181046198 -0.00711106043]
  [0.000220256858 -0.00275785197]
  [-0.00338693848 -0.0107547697]
  ...
  [-0.00256645866 -0.0285590068]
  [-0.00183428475 -0.00623065606]
  [-0.00723056123 -0.00545435]]

 [[0.00181046198 -0.00711106043]
  [0.000220256858 -0.00275785197]
  [-0.00338693848 -0.0107547697]
  ...
  [-0.00256645866 -0.0285590068]
  [-0.00183428475 -0.00623065606]
  [-0.00723056123 -0.00545435]]

 [[0.00181046198 -0.00711106043]
  [0.000220256858 -0.00275785197

score :  [[0.0631072894 0.062584132 0.062744908 ... 0.0624934286 0.0626826733 0.0622588024]
 [0.0624920316 0.0619431436 0.0621010773 ... 0.0620773733 0.0621307902 0.061734803]
 [0.0622540787 0.0616586581 0.0621787421 ... 0.0622700937 0.0622436255 0.0618229657]
 ...
 [0.062515229 0.0619377643 0.0616128333 ... 0.0620536692 0.0618206561 0.0616534725]
 [0.0626060888 0.0618867911 0.0619190894 ... 0.0619351305 0.061844904 0.0616165772]
 [0.0623628907 0.0618639775 0.0618066229 ... 0.0617416576 0.0617284253 0.0614646897]]
pred :  [[[0.00410414767 -0.0135941356]
  [0.00514961826 -0.00158830406]
  [-0.00760037359 -0.00882582]
  ...
  [0.00244056201 -0.0240421798]
  [-0.00335483812 -0.00378171145]
  [-0.000507369405 -0.00321347895]]

 [[0.00410414767 -0.0135941356]
  [0.00514961826 -0.00158830406]
  [-0.00760037359 -0.00882582]
  ...
  [0.00244056201 -0.0240421798]
  [-0.00335483812 -0.00378171145]
  [-0.000507369405 -0.00321347895]]

 [[0.00410414767 -0.0135941356]
  [0.00514961826 -0.0015883040

score :  [[0.0630762428 0.0625942275 0.0625285879 ... 0.0626350269 0.0626341626 0.0624112971]
 [0.0624507181 0.0620295592 0.061965432 ... 0.0619498417 0.0619871169 0.0618247725]
 [0.0625036433 0.0620003305 0.0619243346 ... 0.0621878393 0.0620913 0.0619045]
 ...
 [0.062485408 0.061989896 0.0619601794 ... 0.0618857257 0.0618339702 0.0617166683]
 [0.0624984652 0.0620665886 0.0620656274 ... 0.0619232208 0.0618833452 0.0617747158]
 [0.0622518286 0.0619366914 0.0619547144 ... 0.0619577356 0.0619145036 0.0618470088]]
pred :  [[[0.00618644571 -0.0174608734]
  [0.00972067658 0.000272836071]
  [-0.00881194137 -0.00928185]
  ...
  [0.00250760233 -0.0148165254]
  [-0.002831124 -0.00601677038]
  [0.00155561161 0.00223794486]]

 [[0.00618644571 -0.0174608734]
  [0.00972067658 0.000272836071]
  [-0.00881194137 -0.00928185]
  ...
  [0.00250760233 -0.0148165254]
  [-0.002831124 -0.00601677038]
  [0.00155561161 0.00223794486]]

 [[0.00618644571 -0.0174608734]
  [0.00972067658 0.000272836071]
  [-0.00881

score :  [[0.0630314052 0.0625660643 0.0628377199 ... 0.0626611933 0.0627086908 0.0625674054]
 [0.0625960901 0.0621040426 0.0622947477 ... 0.062121179 0.0621224493 0.0620318055]
 [0.0625624135 0.0620754398 0.0621489622 ... 0.0621263422 0.062175408 0.0620992668]
 ...
 [0.0625986382 0.0621927977 0.062296886 ... 0.0619253069 0.0619428121 0.0618299358]
 [0.0626261458 0.0621678829 0.0622524694 ... 0.0619271956 0.0619149916 0.0618323684]
 [0.0622405857 0.0619507954 0.0619083196 ... 0.0618434437 0.0618693456 0.0618188791]]
pred :  [[[0.00764821656 -0.0227460898]
  [0.0101985317 -0.00153265009]
  [-0.00823468901 -0.0103494497]
  ...
  [0.00257400307 -0.00822076201]
  [-0.00482452754 -0.00310096]
  [0.00369294733 0.0077185249]]

 [[0.00764821656 -0.0227460898]
  [0.0101985317 -0.00153265009]
  [-0.00823468901 -0.0103494497]
  ...
  [0.00257400307 -0.00822076201]
  [-0.00482452754 -0.00310096]
  [0.00369294733 0.0077185249]]

 [[0.00764821656 -0.0227460898]
  [0.0101985317 -0.00153265009]
  [-0.

Training loss (for one batch) at step 20: 0.4740230143070221
score :  [[0.063236095 0.0627089 0.0624545775 ... 0.0626610518 0.0627830103 0.0622959]
 [0.0626105368 0.0619827 0.061789386 ... 0.0624499582 0.0622782148 0.0618547313]
 [0.0625918061 0.0621783473 0.0627507 ... 0.0622288547 0.0621247031 0.0616154037]
 ...
 [0.0624768101 0.061567761 0.062088266 ... 0.0622161068 0.0619675852 0.0620025098]
 [0.0621345118 0.0621613376 0.0623062775 ... 0.0620771162 0.0618215166 0.0618075281]
 [0.0626369715 0.0624471456 0.0619907156 ... 0.0618974864 0.0616595 0.0614526682]]
pred :  [[[0.00871254 -0.0178288538]
  [0.0107660703 -0.00240371842]
  [-0.0039018204 -0.010143375]
  ...
  [0.00132164301 -0.000426961109]
  [-0.00427353615 0.00202253344]
  [0.00444298564 0.00653904444]]

 [[0.00871254 -0.0178288538]
  [0.0107660703 -0.00240371842]
  [-0.0039018204 -0.010143375]
  ...
  [0.00132164301 -0.000426961109]
  [-0.00427353615 0.00202253344]
  [0.00444298564 0.00653904444]]

 [[0.00871254 -0.0178288538

score :  [[0.0631962717 0.0626217 0.0625894666 ... 0.0625059158 0.0626326352 0.0624677949]
 [0.0624411441 0.0618917421 0.061926607 ... 0.0618789308 0.061966829 0.0618557744]
 [0.0625401512 0.0620099343 0.0619543158 ... 0.0618883036 0.0619211122 0.0617537685]
 ...
 [0.0626173466 0.0620771162 0.0620961 ... 0.0619558208 0.0620061904 0.0613559932]
 [0.0625076517 0.0619553477 0.0618871339 ... 0.0619795807 0.0619193837 0.0612732619]
 [0.0622777045 0.06184512 0.061839208 ... 0.0616720542 0.061777249 0.061217051]]
pred :  [[[0.0139072882 -0.00812381878]
  [0.0123955924 0.00189098436]
  [0.0038236985 -0.00446411408]
  ...
  [-0.00189349498 0.00791911595]
  [-0.00738760922 0.00265082577]
  [0.000178130635 0.00452391943]]

 [[0.0139072882 -0.00812381878]
  [0.0123955924 0.00189098436]
  [0.0038236985 -0.00446411408]
  ...
  [-0.00189349498 0.00791911595]
  [-0.00738760922 0.00265082577]
  [0.000178130635 0.00452391943]]

 [[0.0139072882 -0.00812381878]
  [0.0123955924 0.00189098436]
  [0.00382369

score :  [[0.0631659627 0.0626992062 0.0627035722 ... 0.0622864701 0.0621974356 0.0625307411]
 [0.0625942275 0.0621166155 0.0621154793 ... 0.0618505217 0.0625199378 0.0622437634]
 [0.0625993758 0.0621169135 0.0621003322 ... 0.0624108352 0.0625573695 0.0623091795]
 ...
 [0.062642239 0.0622499958 0.0622927509 ... 0.0620492846 0.062124379 0.0619695298]
 [0.0624428242 0.0620908365 0.0620293804 ... 0.0619808622 0.0621107519 0.0619706176]
 [0.0622023232 0.061859522 0.0617884062 ... 0.0618593134 0.0619804338 0.0618335605]]
pred :  [[[0.0129515138 0.00525994645]
  [0.0105924923 0.00559607148]
  [0.0080298055 0.0019803734]
  ...
  [-0.00352501636 0.0117605198]
  [-0.0080468161 0.00208375766]
  [-0.00582986604 0.00193243078]]

 [[0.0129515138 0.00525994645]
  [0.0105924923 0.00559607148]
  [0.0080298055 0.0019803734]
  ...
  [-0.00352501636 0.0117605198]
  [-0.0080468161 0.00208375766]
  [-0.00582986604 0.00193243078]]

 [[0.0129515138 0.00525994645]
  [0.0105924923 0.00559607148]
  [0.008029805

score :  [[0.0629823133 0.0625131577 0.0627245903 ... 0.0624088719 0.0624541864 0.0623201057]
 [0.0624327213 0.0617405437 0.0622849 ... 0.0618132278 0.0618944541 0.061729189]
 [0.0625073537 0.061831627 0.062295638 ... 0.0616770647 0.0621479228 0.0619106591]
 ...
 [0.0625340641 0.0621085577 0.062666513 ... 0.0622202083 0.0623164326 0.0618399642]
 [0.0625383779 0.0624514446 0.0630295724 ... 0.0622980744 0.0622437634 0.0617900044]
 [0.0623241179 0.0626834 0.0628085211 ... 0.0621299967 0.0619390383 0.0615424812]]
pred :  [[[0.00588048249 0.0154897971]
  [0.00631220778 0.0105170161]
  [0.007310268 0.00768711325]
  ...
  [-0.00819037296 0.00988989882]
  [-0.0105354 0.00119052641]
  [-0.0119248182 -0.00206723018]]

 [[0.00588048249 0.0154897971]
  [0.00631220778 0.0105170161]
  [0.007310268 0.00768711325]
  ...
  [-0.00819037296 0.00988989882]
  [-0.0105354 0.00119052641]
  [-0.0119248182 -0.00206723018]]

 [[0.00588048249 0.0154897971]
  [0.00631220778 0.0105170161]
  [0.007310268 0.00768711

score :  [[0.0631025732 0.062696375 0.0627678111 ... 0.0624945723 0.0624280386 0.0623247065]
 [0.0625973344 0.0620794855 0.0622354262 ... 0.0620655492 0.0619926676 0.0618511103]
 [0.0630295053 0.0617550611 0.061997965 ... 0.0623478889 0.0621873066 0.061967995]
 ...
 [0.0627355278 0.0618479066 0.0624234863 ... 0.0622740276 0.0621345043 0.0616236553]
 [0.0625829846 0.0618527606 0.0622455962 ... 0.0618387572 0.0614280179 0.0614132583]
 [0.0623673238 0.0616897792 0.0618709438 ... 0.0618259385 0.0615472347 0.0618743747]]
pred :  [[[-0.00730336877 0.0169384014]
  [0.0158631057 0.00506776851]
  [-0.00510956906 0.00187509903]
  ...
  [0.00214346172 0.00641983934]
  [-0.00349782687 -6.32289448e-05]
  [-0.00577136502 -0.012930234]]

 [[-0.00730336877 0.0169384014]
  [0.0158631057 0.00506776851]
  [-0.00510956906 0.00187509903]
  ...
  [0.00214346172 0.00641983934]
  [-0.00349782687 -6.32289448e-05]
  [-0.00577136502 -0.012930234]]

 [[-0.00730336877 0.0169384014]
  [0.0158631057 0.00506776851]
 

score :  [[0.0631483 0.0626686215 0.0628435388 ... 0.0627934933 0.0628184453 0.0623763651]
 [0.0626117215 0.0621977933 0.0622067899 ... 0.0621876977 0.0620918944 0.061842408]
 [0.0625400469 0.0620171875 0.0619426034 ... 0.0621220507 0.0621613599 0.0617216416]
 ...
 [0.062447682 0.061936643 0.0620828681 ... 0.0620798506 0.062055517 0.0617196187]
 [0.0627389774 0.0620282553 0.0618805923 ... 0.0617786311 0.0615769364 0.0611871555]
 [0.0624947809 0.0619931109 0.0615577251 ... 0.0614617579 0.061358735 0.0614172928]]
pred :  [[[-0.0173956938 0.0126249343]
  [0.0216507278 -0.000619221944]
  [-0.00899502728 -0.00436212029]
  ...
  [0.00921194907 0.00495125121]
  [0.00152860512 0.00102219451]
  [0.00117643364 -0.0179328527]]

 [[-0.0173956938 0.0126249343]
  [0.0216507278 -0.000619221944]
  [-0.00899502728 -0.00436212029]
  ...
  [0.00921194907 0.00495125121]
  [0.00152860512 0.00102219451]
  [0.00117643364 -0.0179328527]]

 [[-0.0173956938 0.0126249343]
  [0.0216507278 -0.000619221944]
  [-0.0

score :  [[0.0629264265 0.0626069233 0.0624226034 ... 0.0630696043 0.0628548563 0.0622752495]
 [0.0622845478 0.0617687851 0.061617922 ... 0.0625173524 0.0623495653 0.0618205592]
 [0.0625506788 0.0619371422 0.0617653579 ... 0.0625780076 0.0623321682 0.061829336]
 ...
 [0.0626414493 0.0623693578 0.062397182 ... 0.0621551089 0.0620466582 0.0619045794]
 [0.0628043041 0.0622609593 0.0622015223 ... 0.0621453971 0.0620378293 0.0618840456]
 [0.0624365322 0.0620371 0.0618370287 ... 0.062073525 0.0619555376 0.0617378]]
pred :  [[[-0.0177829582 0.00399876]
  [0.0156691261 -0.00240876386]
  [-0.00330009591 -0.00669549685]
  ...
  [0.00361320516 0.00561158173]
  [0.00601552101 -0.00143825565]
  [-0.00134905754 -0.011514632]]

 [[-0.0177829582 0.00399876]
  [0.0156691261 -0.00240876386]
  [-0.00330009591 -0.00669549685]
  ...
  [0.00361320516 0.00561158173]
  [0.00601552101 -0.00143825565]
  [-0.00134905754 -0.011514632]]

 [[-0.0177829582 0.00399876]
  [0.0156691261 -0.00240876386]
  [-0.0033000959

score :  [[0.0631274953 0.0626504868 0.0626862198 ... 0.0626295134 0.0626238808 0.0624155924]
 [0.0626428574 0.0620572753 0.062138997 ... 0.0619678758 0.0619782582 0.0618149303]
 [0.0624639727 0.0619512908 0.0619223565 ... 0.0619507395 0.0619764291 0.0618379228]
 ...
 [0.0627787188 0.0621390268 0.0620405823 ... 0.0618017 0.062092606 0.0619885959]
 [0.0626240596 0.0619949549 0.0618859492 ... 0.0621418543 0.0621807836 0.0619263239]
 [0.0621630251 0.061755795 0.0617024116 ... 0.0616775267 0.0618538409 0.0615371391]]
pred :  [[[-0.0130202994 -0.00115084043]
  [0.0041560363 -0.0010906423]
  [0.00689154444 -0.00468683569]
  ...
  [-0.00871529616 0.00712845428]
  [0.00344649539 -0.00407781638]
  [-0.0109423557 0.000697791]]

 [[-0.0130202994 -0.00115084043]
  [0.0041560363 -0.0010906423]
  [0.00689154444 -0.00468683569]
  ...
  [-0.00871529616 0.00712845428]
  [0.00344649539 -0.00407781638]
  [-0.0109423557 0.000697791]]

 [[-0.0130202994 -0.00115084043]
  [0.0041560363 -0.0010906423]
  [0.00

score :  [[0.0632484332 0.0626214 0.0625160411 ... 0.0623673797 0.0625869632 0.0623715]
 [0.0625809804 0.0620338209 0.0620835125 ... 0.0616742969 0.0619341545 0.0618746467]
 [0.0625457689 0.0618884638 0.0619457662 ... 0.0619562306 0.0617655404 0.0618105941]
 ...
 [0.0624980964 0.0619073063 0.0619975217 ... 0.0618598498 0.0618273839 0.0617259778]
 [0.0624152273 0.0618966073 0.0620376579 ... 0.0619765893 0.0618610121 0.0616101921]
 [0.0622201487 0.0618264601 0.0618590042 ... 0.0618796609 0.0618399903 0.0617545545]]
pred :  [[[-0.0117626796 -0.00269910181]
  [-0.00728078932 -0.000357715646]
  [0.0135988537 -0.00262277597]
  ...
  [-0.0173513088 0.00282138027]
  [0.00290690153 -0.0029182604]
  [-0.0163815245 0.0089711342]]

 [[-0.0117626796 -0.00269910181]
  [-0.00728078932 -0.000357715646]
  [0.0135988537 -0.00262277597]
  ...
  [-0.0173513088 0.00282138027]
  [0.00290690153 -0.0029182604]
  [-0.0163815245 0.0089711342]]

 [[-0.0117626796 -0.00269910181]
  [-0.00728078932 -0.000357715646]

score :  [[0.0632015392 0.0626560748 0.0626478344 ... 0.0626164749 0.0626328439 0.0624596179]
 [0.0625704527 0.0620246381 0.0620169677 ... 0.0619796924 0.0620027967 0.0618558228]
 [0.0625548288 0.0620125383 0.0620042235 ... 0.0619629398 0.0619824789 0.0618405342]
 ...
 [0.0622072071 0.0620213039 0.0620528981 ... 0.0619560555 0.0619732477 0.0618229248]
 [0.0622722507 0.0618494898 0.0619414896 ... 0.0619693175 0.0619804524 0.0618222654]
 [0.0622811578 0.0619380809 0.0619716346 ... 0.0619288608 0.0619412847 0.0618432239]]
pred :  [[[-0.009457618 -0.00641555246]
  [-0.0169364661 -9.26328357e-06]
  [0.0149646979 -0.000384583836]
  ...
  [-0.0205074754 -0.00177615602]
  [0.00243209745 -0.00382111198]
  [-0.0212750509 0.0136223808]]

 [[-0.009457618 -0.00641555246]
  [-0.0169364661 -9.26328357e-06]
  [0.0149646979 -0.000384583836]
  ...
  [-0.0205074754 -0.00177615602]
  [0.00243209745 -0.00382111198]
  [-0.0212750509 0.0136223808]]

 [[-0.009457618 -0.00641555246]
  [-0.0169364661 -9.2632835

Training loss (for one batch) at step 50: 0.47027140855789185
score :  [[0.0630999729 0.0626176894 0.0626115203 ... 0.0625758246 0.0625983179 0.0624012388]
 [0.0625323951 0.0620148 0.0620129555 ... 0.0619743 0.0620112307 0.0618334748]
 [0.0624997616 0.0619817227 0.0620301031 ... 0.0619510077 0.0619873032 0.0618161932]
 ...
 [0.062505722 0.0619565472 0.0617899 ... 0.0617501847 0.062432956 0.0622414239]
 [0.0624984205 0.0619887635 0.0617990457 ... 0.0618296228 0.062496949 0.0621946231]
 [0.0622588694 0.0619035065 0.0617227778 ... 0.0618762262 0.0623254403 0.062061362]]
pred :  [[[-0.00352650788 -0.0118080806]
  [-0.0180133767 1.28695974e-05]
  [0.0105470978 0.000420857]
  ...
  [-0.0161872953 -0.00408940669]
  [0.00369278435 -0.00294855237]
  [-0.0190014988 0.0160602927]]

 [[-0.00352650788 -0.0118080806]
  [-0.0180133767 1.28695974e-05]
  [0.0105470978 0.000420857]
  ...
  [-0.0161872953 -0.00408940669]
  [0.00369278435 -0.00294855237]
  [-0.0190014988 0.0160602927]]

 [[-0.00352650788 

score :  [[0.0630580485 0.0626026 0.0626110435 ... 0.0625791922 0.0625374839 0.0624443442]
 [0.0625050813 0.0619752966 0.0620050095 ... 0.0620064884 0.0619126447 0.0618327521]
 [0.0625468493 0.0619717874 0.0620033368 ... 0.0619559 0.0619026385 0.0618664697]
 ...
 [0.0625166446 0.0620806143 0.0619869754 ... 0.0620503053 0.0621459633 0.061986398]
 [0.0624797381 0.0620573945 0.0619833283 ... 0.0619577132 0.0619415 0.0617916]
 [0.0622567572 0.0619697198 0.061899025 ... 0.0618320145 0.0618889257 0.061782524]]
pred :  [[[-0.000519574503 -0.0155260582]
  [-0.0102325883 -0.000204104726]
  [0.000588879688 0.00133707]
  ...
  [-0.00361650204 -0.00330657372]
  [0.00402891729 -0.00194310385]
  [-0.0109015014 0.0133222668]]

 [[-0.000519574503 -0.0155260582]
  [-0.0102325883 -0.000204104726]
  [0.000588879688 0.00133707]
  ...
  [-0.00361650204 -0.00330657372]
  [0.00402891729 -0.00194310385]
  [-0.0109015014 0.0133222668]]

 [[-0.000519574503 -0.0155260582]
  [-0.0102325883 -0.000204104726]
  [0.0

score :  [[0.0631479695 0.0627232715 0.0627277419 ... 0.0626508 0.062642023 0.0624156222]
 [0.0625597611 0.0620513074 0.0620507561 ... 0.0618567318 0.0619825944 0.0618178248]
 [0.0626864 0.0620630085 0.0620365366 ... 0.0618929192 0.061969 0.0617789961]
 ...
 [0.062508665 0.0619598851 0.0619093589 ... 0.0621323809 0.0620907173 0.0618907399]
 [0.0625209138 0.0619681515 0.0619746633 ... 0.0621204153 0.0620814897 0.0618884563]
 [0.0623023249 0.0618398488 0.0618834831 ... 0.0619407557 0.0619105622 0.0617697649]]
pred :  [[[0.00484152092 -0.0116566066]
  [-0.00775144622 0.00272233272]
  [0.000706272665 0.00732935593]
  ...
  [0.00112356758 -0.000454063527]
  [-0.000841724395 -0.000540040899]
  [-0.007253021 0.0128232352]]

 [[0.00484152092 -0.0116566066]
  [-0.00775144622 0.00272233272]
  [0.000706272665 0.00732935593]
  ...
  [0.00112356758 -0.000454063527]
  [-0.000841724395 -0.000540040899]
  [-0.007253021 0.0128232352]]

 [[0.00484152092 -0.0116566066]
  [-0.00775144622 0.00272233272]
  

score :  [[0.0631439909 0.0628543422 0.0629407242 ... 0.062582992 0.0626106784 0.0624469221]
 [0.0626113117 0.0622899197 0.0623201653 ... 0.0619314276 0.0619944185 0.061947044]
 [0.062565051 0.0621776655 0.062003985 ... 0.0621551462 0.0619800165 0.0619835332]
 ...
 [0.0626561195 0.0620727614 0.0620618872 ... 0.0621177331 0.0621658526 0.0617859252]
 [0.062704742 0.062217392 0.0622302927 ... 0.0622508191 0.0621617697 0.0619762689]
 [0.0624380298 0.061969582 0.0619228669 ... 0.0620064 0.0620002896 0.0618885681]]
pred :  [[[0.00715537835 -0.00157292653]
  [-0.00278932229 0.00285662897]
  [-0.00229998678 0.00741109252]
  ...
  [0.00718818419 0.00688045565]
  [-0.00225335686 0.00258146646]
  [-0.00220801029 0.00923575088]]

 [[0.00715537835 -0.00157292653]
  [-0.00278932229 0.00285662897]
  [-0.00229998678 0.00741109252]
  ...
  [0.00718818419 0.00688045565]
  [-0.00225335686 0.00258146646]
  [-0.00220801029 0.00923575088]]

 [[0.00715537835 -0.00157292653]
  [-0.00278932229 0.00285662897]
 

KeyboardInterrupt: 

In [ ]:
train.result_test(config, ['train'])

In [ ]:
from models.cnn_geo import CNN_geo
from data_loader import load_data
import numpy as np
from matplotlib import pyplot as plt

In [ ]:
model = CNN_geo(config['backbone'])
ckpt_dir = os.path.join(
        'checkpoints', config['model_name'], config['exp_desc'])
ckpt = os.path.join(ckpt_dir, "{}-{}.h5".format(config['model_name'], str(config['train']['epochs'])))
model.load(ckpt)

In [ ]:
model.layers

In [ ]:
model.layers[2](np.ones([1, 16,16,16,16]))

In [ ]:
datasets = load_data(['train'], config)
ds = datasets['train'].batch(1)
for image_A, image_B, parameters in ds.take(1):
    image_A = image_A.numpy()
    image_B = image_B.numpy()
    parameters = parameters.numpy()

In [ ]:
image_A.shape, image_B.shape

x = model.layers[0](image_A)
y = model.layers[0](image_B)

In [ ]:
x

In [ ]:
score = model.layers[1](x, y)

In [ ]:
model.layers[2](score)

In [ ]:
vgg = tf.keras.applications.VGG16(weights='imagenet', input_shape=(64, 64, 3), include_top=False)

In [ ]:
model = tf.keras.Model(inputs=vgg.layers[0].input, outputs=vgg.layers[9].output)

In [ ]:
model.summary()