In [1]:
import os, sys
root_path = os.path.abspath('.').split('jupyters')[0]
sys.path.append(root_path)

In [2]:
import json
import argparse
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt

from functools import partial

In [3]:
map_size = (10, 10)
#py_func = partial(data_process, map_size = map_size)

In [4]:
correlations = np.zeros(map_size, np.float32)

In [5]:
correlations

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [6]:
def make_corr_map(mp, map_size):
    #mp = mp.numpy()
    correlations = np.zeros(map_size, np.float32)
    for i in range(map_size[0]):
        for j in range(map_size[1]):
            if i+mp == j:
                correlations[i,j] += 1
    return correlations

In [7]:
correlations = make_corr_map(0, map_size)
print(correlations)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [8]:
correlations = make_corr_map(1, map_size)
print(correlations)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
correlations = make_corr_map(2, map_size)
print(correlations)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [10]:
correlations = make_corr_map(-1, map_size)
print(correlations)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [11]:
correlations = make_corr_map(-2, map_size)
print(correlations)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [12]:
def gen_integer():
    while True:
        yield tf.random.uniform(shape=[1], minval = -10, maxval=11, dtype=tf.int32, seed=10)

In [13]:
def data_process(mp, map_size):
    mp = mp.numpy()
    correlations = np.zeros(map_size, np.float32)
    for i in range(map_size[0]):
        for j in range(map_size[1]):
            if i+mp == j:
                correlations[i,j] += 1
    return mp, correlations

In [14]:
py_func = partial(data_process, map_size = map_size)
def map_function(motion_paramters):
    return tf.py_function(py_func, [motion_paramters], [tf.float32, tf.float32])

In [15]:
ds = tf.data.Dataset.from_generator(gen_integer, output_types=tf.int32)
ds = ds.map(map_function)
ds = ds.batch(100)

In [16]:
for mp, corr in ds.take(1):
    print(mp)
    print(min(mp), max(mp))
    print(corr)

tf.Tensor(
[[  2.]
 [-10.]
 [ -6.]
 [ -3.]
 [  7.]
 [  6.]
 [ -5.]
 [ -5.]
 [  3.]
 [ -1.]
 [ -2.]
 [  6.]
 [ -7.]
 [ 10.]
 [  0.]
 [ -4.]
 [  7.]
 [ -1.]
 [  2.]
 [  0.]
 [  9.]
 [ -4.]
 [  9.]
 [  1.]
 [ -6.]
 [ 10.]
 [  7.]
 [  7.]
 [ 10.]
 [ -6.]
 [  8.]
 [ -2.]
 [ -2.]
 [  0.]
 [  1.]
 [ -6.]
 [-10.]
 [  9.]
 [ -5.]
 [ -8.]
 [-10.]
 [  7.]
 [ -6.]
 [  5.]
 [  4.]
 [ -3.]
 [  7.]
 [ 10.]
 [ -8.]
 [  3.]
 [  2.]
 [ -3.]
 [ -1.]
 [ -8.]
 [ -8.]
 [ 10.]
 [ -6.]
 [  2.]
 [  2.]
 [ -3.]
 [  6.]
 [ -9.]
 [ 10.]
 [  9.]
 [  9.]
 [ -1.]
 [  0.]
 [  0.]
 [  8.]
 [ -4.]
 [ -7.]
 [ -2.]
 [ -8.]
 [  4.]
 [ -8.]
 [  9.]
 [  0.]
 [ -7.]
 [ -5.]
 [  1.]
 [  5.]
 [  0.]
 [  5.]
 [  4.]
 [ -5.]
 [ -6.]
 [ -5.]
 [  0.]
 [ -7.]
 [  7.]
 [ -5.]
 [  9.]
 [ -1.]
 [ -9.]
 [  6.]
 [  2.]
 [ -6.]
 [ -4.]
 [  9.]
 [ 10.]], shape=(100, 1), dtype=float32)
tf.Tensor([-10.], shape=(1,), dtype=float32) tf.Tensor([10.], shape=(1,), dtype=float32)
tf.Tensor(
[[[0. 0. 1. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0

In [17]:
layers = tf.keras.layers
#dir(layers)

In [18]:
def loss_fn(pred, label):
    loss = tf.sqrt(tf.pow(pred - label, 2))
    loss_mean = tf.reduce_mean(loss)
    return loss_mean

In [ ]:
regressor = tf.keras.Sequential([layers.Conv1D(3, 3),
                             layers.Conv1D(3, 3),
                             layers.Flatten(),
                             layers.Dense(1)])
pred = regressor(np.ones([16,map_size[0],map_size[1]]))
pred = tf.reshape(pred, [-1, 1])
regressor.summary()

i = 0
x = []
x_loss1 = []
optimizer = tf.keras.optimizers.SGD(learning_rate=0.05)
for epoch in range(4000):
    i+= 1
    x.append(i)
    for mp, correlations in ds.take(1):
        with tf.GradientTape() as tape:
            pred = regressor(correlations)
            pred = tf.reshape(pred, [-1, 1])
            loss = loss_fn(pred, mp)
            x_loss1.append(loss)
        gradients = tape.gradient(loss, regressor.trainable_variables)
        optimizer.apply_gradients(zip(gradients, regressor.trainable_variables)) 
        if i % 10 == 0:
            print(i, "iter loss : ", loss.numpy())


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              multiple                  93        
_________________________________________________________________
conv1d_1 (Conv1D)            multiple                  30        
_________________________________________________________________
flatten (Flatten)            multiple                  0         
__________________________

2420 iter loss :  1.1817261
2430 iter loss :  1.6653708
2440 iter loss :  0.9867492
2450 iter loss :  1.1893284
2460 iter loss :  1.0412598
2470 iter loss :  1.0500995
2480 iter loss :  0.6134098
2490 iter loss :  1.2944516
2500 iter loss :  1.0083756
2510 iter loss :  1.1965901
2520 iter loss :  1.1261816
2530 iter loss :  1.4677978
2540 iter loss :  1.5881397
2550 iter loss :  1.2386605
2560 iter loss :  1.3636844
2570 iter loss :  0.85446286
2580 iter loss :  1.0803494
2590 iter loss :  1.2980953
2600 iter loss :  1.8345194
2610 iter loss :  1.0737702
2620 iter loss :  1.3893772
2630 iter loss :  1.4651
2640 iter loss :  1.2454342
2650 iter loss :  1.2154254
2660 iter loss :  1.4736372
2670 iter loss :  1.6611444
2680 iter loss :  1.7089283
2690 iter loss :  1.1692591
2700 iter loss :  0.9537831
2710 iter loss :  0.9321528
2720 iter loss :  1.0528625
2730 iter loss :  0.7808732


In [ ]:
regressor = tf.keras.Sequential([layers.Conv1D(5, 3),
                             layers.Conv1D(3, 3),
                             layers.Flatten(),
                             layers.Dense(1)])
pred = regressor(np.ones([16,10,10]))
pred = tf.reshape(pred, [-1, 1])
regressor.summary()

i = 0
x = []
x_loss2 = []
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
for epoch in range(4000):
    i+= 1
    x.append(i)
    for mp, correlations in ds.take(1):
        with tf.GradientTape() as tape:
            pred = regressor(correlations)
            pred = tf.reshape(pred, [-1, 1])
            loss = loss_fn(pred, mp)
            x_loss2.append(loss)
        gradients = tape.gradient(loss, regressor.trainable_variables)
        optimizer.apply_gradients(zip(gradients, regressor.trainable_variables)) 
        if i % 10 == 0:
            print(i, "iter loss : ", loss.numpy())

In [ ]:
regressor = tf.keras.Sequential([layers.Conv1D(3, 3),
                             layers.Conv1D(5, 3),
                             layers.Flatten(),
                             layers.Dense(1)])
pred = regressor(np.ones([16,10,10]))
pred = tf.reshape(pred, [-1, 1])
regressor.summary()

i = 0
x = []
x_loss3 = []
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
for epoch in range(4000):
    i+= 1
    x.append(i)
    for mp, correlations in ds.take(1):
        with tf.GradientTape() as tape:
            pred = regressor(correlations)
            pred = tf.reshape(pred, [-1, 1])
            loss = loss_fn(pred, mp)
            x_loss3.append(loss)
        gradients = tape.gradient(loss, regressor.trainable_variables)
        optimizer.apply_gradients(zip(gradients, regressor.trainable_variables)) 
        if i % 10 == 0:
            print(i, "iter loss : ", loss.numpy())

In [ ]:

fig = plt.figure()
ax1 = fig.add_subplot(111)
#ax2 = fig.add_subplot(122)
ax1.title.set_text("training loss")
ax1.set_xlabel("epoch")
ax1.set_ylabel("training loss")
ax1.plot(np.array(x), np.array(x_loss1), label="3,3")
ax1.plot(np.array(x), np.array(x_loss2), label="5,3")
ax1.plot(np.array(x), np.array(x_loss3), label="3,5")
plt.legend(loc=2)

# ax2.title.set_text("std-dev of correlations")
# ax2.set_xlabel("epoch")
# ax2.set_ylabel("std-dev")
# ax2.plot(np.array(x), np.array(y_score_std))

In [ ]:
correlations = make_corr_map(3, map_size)
correlations = correlations[np.newaxis, :]
print(correlations)

In [ ]:
for mp in range(-3, 4):
    print("mp : {}".format(mp))
    correlations = make_corr_map(mp, map_size)
    print("correlation map : {}".format(correlations))
    correlations = correlations[np.newaxis, :]
    print("pred : {}".format(regressor(correlations)))

In [ ]:
correlations = make_corr_map(0, map_size)
correlations = correlations[np.newaxis, :]
print(correlations)

In [ ]:
x0 = regressor.layers[0](correlations)
print(x0)

In [ ]:
x1 = regressor.layers[1](x0)
print(x1)

In [ ]:
x2 = regressor.layers[2](x1)
print(x2)

In [ ]:
print(regressor.layers[0].get_weights())

In [ ]:
print(regressor.layers[1].get_weights())

In [ ]:
print(regressor.layers[3].get_weights())